# Generated by Django 4.2.3 on 2025-01-24 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='completed',
        ),
        migrations.AddField(
            model_name='progress',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='progress',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='habits.habit'),
        ),
    ]
