# Generated by Django 4.2.3 on 2025-01-24 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0003_remove_progress_completed_progress_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='badge',
            new_name='badges',
        ),
        migrations.AddField(
            model_name='progress',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='badge',
            name='criteria',
            field=models.CharField(help_text='Criteria for earning this badge', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='progress',
            constraint=models.UniqueConstraint(fields=('habit', 'date'), name='unique_progress_per_habit_per_day'),
        ),
    ]
